alias gs='git status'
alias gk='gitk --all'
alias fcpp='find . -name "*.cpp"'
#alias ip='ipython -i'
alias ipp='~/.local/bin/ipython -i'
set -o ignoreeof
alias rm='rm -i'
alias mv='mv -i'
alias gd='git diff'
alias gba='git branch -a'
#alias gut='git ls-files --other --exclude-standard'
PATH=.:~/bin/:~/.local/bin/:$PATH
alias ipnb='~/.local/bin/ipython notebook --pylab inline'
alias kp='~/.local/bin/kernprof.py'
alias ptest='python tests/test_fmm.py'
alias pbuild='python setup.py install --user --record install.log && ptest'
alias nt='nosetests -v'
alias ipnb='python /c/python27/scripts/ipython-script.py notebook --pylab inline'
